name: lyrink

services:
  lyrink-server:
    container_name: lyrink
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - uploads:/app/uploads
    restart: unless-stopped
    environment:
      - GIN_MODE=release

volumes:
  uploads:
